a = input("Give a number: ")
b = input("Give a second number: ")
a = int(a)
b = int(b)
print(f"{a} + {b} = {a + b}")
print(f"{a} - {b} = {a - b}")
print(f"{a} * {b} = {a*b}")
print(f"{a} / {b} = {a/b}")
print(f"{a} % {b} = {a%b}")
print(f"{a} ** {b} = {a**b}")
print(f"{a} // {b} = {a//b}")
print(f"{a} == {b} = {a == b}")
print(f"{a} != {b} = {a != b}")
print(f"{a} > {b} = {a>b}")
print(f"{a} < {b} = {a<b}")
print(f"{a} >= {b} = {a>=b}")
print(f"{a} <= {b} = {a<=b}")
print(f"{a} & {b} = {a & b}")
print(f"{a} | {b} = {a | b}")
print(f"{a} ^ {b} = {a ^ b}")
print(f"~{a} = {~a}")
print(f"{a} << {b} = {a << b}")
print(f"{a} >> {b} = {a >> b}")
print(f"{a} is {b} = {a is b}")
print(f"{a} is not {b} = {a is not b}")
a = str(a)
b = str(b)
print(f"{a} in {b} = {a in b}")
print(f"{a} not in {b} = {a not in b}")